// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyApi.Data;

#nullable disable

namespace MyApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230621005304_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JogoUsuario", b =>
                {
                    b.Property<int>("JogoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("JogoId", "UsuarioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("JogoUsuario");
                });

            modelBuilder.Entity("MyApi.Models.Favorito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("JogoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JogoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Favoritos");
                });

            modelBuilder.Entity("MyApi.Models.Jogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataL")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Desenvolvedor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Jogos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataL = new DateTime(2021, 10, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Far Cry 6 é um jogo de tiro em primeira pessoa de mundo aberto desenvolvido pela Ubisoft Toronto. Ambientado na ilha fictícia de Yara, os jogadores assumem o papel de Dani Rojas, um guerrilheiro lutando contra o regime opressivo do ditador Anton Castillo. Com um vasto mundo para explorar, combates intensos e uma narrativa envolvente, Far Cry 6 oferece uma experiência cheia de ação e aventura.",
                            Desenvolvedor = "Ubisoft Toronto",
                            Genero = "Tiro, Ação",
                            Nome = "Far Cry 6"
                        },
                        new
                        {
                            Id = 2,
                            DataL = new DateTime(2018, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Bloons TD6 é um jogo de estratégia em que os jogadores devem defender seu território contra ondas de balões invasores. O jogo apresenta torres de defesa com habilidades únicas, diversos mapas e modos de jogo, oferecendo uma experiência desafiadora e divertida.",
                            Desenvolvedor = "Ninja Kiwi",
                            Genero = "Estratégia",
                            Nome = "Bloons TD6"
                        },
                        new
                        {
                            Id = 3,
                            DataL = new DateTime(2010, 5, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Red Dead Redemption é um jogo de ação e aventura em mundo aberto ambientado no Velho Oeste. Os jogadores assumem o papel de um pistoleiro chamado John Marston, que deve caçar criminosos e enfrentar desafios em uma história épica. O jogo oferece um vasto mundo para explorar, com muitas missões e atividades para realizar.",
                            Desenvolvedor = "Rockstar San Diego",
                            Genero = "Ação, Aventura",
                            Nome = "Red Dead Redemption"
                        },
                        new
                        {
                            Id = 4,
                            DataL = new DateTime(2020, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Valorant é um jogo de tiro tático em primeira pessoa desenvolvido pela Riot Games. No jogo, duas equipes competem em partidas de ataque e defesa, utilizando personagens com habilidades únicas. Com combates estratégicos e trabalho em equipe, Valorant oferece uma experiência de jogo emocionante e competitiva.",
                            Desenvolvedor = "Riot Games",
                            Genero = "Tiro em primeira pessoa",
                            Nome = "Valorant"
                        },
                        new
                        {
                            Id = 5,
                            DataL = new DateTime(2012, 8, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Counter-Strike: Global Offensive é um jogo de tiro em primeira pessoa competitivo. Os jogadores se juntam a equipes terroristas ou antiterroristas e participam de partidas intensas em diversos modos de jogo. Com uma jogabilidade estratégica e habilidades individuais em teste, CS:GO continua sendo um dos jogos mais populares do gênero.",
                            Desenvolvedor = "Valve",
                            Genero = "Tiro em primeira pessoa",
                            Nome = "Counter-Strike: Global Offensive"
                        },
                        new
                        {
                            Id = 6,
                            DataL = new DateTime(2009, 10, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "League of Legends é um jogo online de batalha multiplayer em arenas (MOBA). Duas equipes de campeões únicos se enfrentam em intensas batalhas, com o objetivo de destruir o nexus inimigo. Com estratégia, trabalho em equipe e habilidades individuais, League of Legends é um dos jogos mais populares e competitivos do mundo.",
                            Desenvolvedor = "Riot Games",
                            Genero = "MOBA",
                            Nome = "League of Legends"
                        },
                        new
                        {
                            Id = 7,
                            DataL = new DateTime(2013, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Dota 2 é um jogo online de batalha multiplayer em arenas (MOBA) desenvolvido pela Valve. Os jogadores formam equipes e batalham para destruir o Ancião inimigo, com a ajuda de heróis poderosos e estratégias elaboradas. Com uma grande variedade de heróis e uma comunidade ativa, Dota 2 oferece uma experiência desafiadora e competitiva.",
                            Desenvolvedor = "Valve",
                            Genero = "MOBA",
                            Nome = "Dota 2"
                        },
                        new
                        {
                            Id = 8,
                            DataL = new DateTime(2011, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Minecraft é um jogo de construção e aventura em um mundo sandbox. Os jogadores podem explorar, construir estruturas e objetos, coletar recursos e enfrentar criaturas em um ambiente pixelizado. Com sua jogabilidade criativa e possibilidades infinitas, Minecraft se tornou um fenômeno mundial.",
                            Desenvolvedor = "Mojang Studios",
                            Genero = "Sandbox, Aventura",
                            Nome = "Minecraft"
                        },
                        new
                        {
                            Id = 9,
                            DataL = new DateTime(2013, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Grand Theft Auto V é um jogo de ação e aventura em mundo aberto desenvolvido pela Rockstar North. Nele, os jogadores podem explorar a cidade fictícia de Los Santos, realizar missões, participar de atividades e interagir com personagens diversos.",
                            Desenvolvedor = "Rockstar North",
                            Genero = "Ação, Aventura",
                            Nome = "Grand Theft Auto V"
                        },
                        new
                        {
                            Id = 10,
                            DataL = new DateTime(2017, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Fortnite é um jogo de tiro em terceira pessoa com elementos de construção. Os jogadores são colocados em um mapa onde devem lutar contra outros jogadores, enquanto constroem estruturas e procuram por recursos. Com modos de jogo variados e eventos frequentes, Fortnite se tornou um dos jogos mais populares do mundo.",
                            Desenvolvedor = "Epic Games",
                            Genero = "Battle Royale, Construção",
                            Nome = "Fortnite"
                        },
                        new
                        {
                            Id = 11,
                            DataL = new DateTime(2004, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "World of Warcraft é um MMORPG ambientado no mundo de fantasia de Azeroth. Os jogadores podem criar personagens, explorar vastas terras, realizar missões, participar de batalhas épicas e interagir com outros jogadores. Com uma história rica e constantes atualizações, World of Warcraft continua sendo um dos jogos mais populares do gênero.",
                            Desenvolvedor = "Blizzard Entertainment",
                            Genero = "MMORPG",
                            Nome = "World of Warcraft"
                        },
                        new
                        {
                            Id = 12,
                            DataL = new DateTime(2014, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "The Sims 4 é um jogo de simulação de vida em que os jogadores podem criar e controlar personagens virtuais, chamados Sims. Eles podem construir casas, desenvolver relacionamentos, buscar carreiras e viver diversas experiências. Com sua jogabilidade cativante e ferramentas de criação, The Sims 4 é um dos jogos mais populares da franquia.",
                            Desenvolvedor = "Maxis",
                            Genero = "Simulação",
                            Nome = "The Sims 4"
                        },
                        new
                        {
                            Id = 13,
                            DataL = new DateTime(2020, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Call of Duty: Warzone é um jogo de battle royale gratuito que faz parte da franquia Call of Duty. Os jogadores são lançados em um mapa vasto onde devem lutar contra outros jogadores para serem o último sobrevivente. Com um combate intenso e diversas armas e veículos, Warzone oferece uma experiência emocionante.",
                            Desenvolvedor = "Infinity Ward",
                            Genero = "Battle Royale, Tiro",
                            Nome = "Call of Duty: Warzone"
                        },
                        new
                        {
                            Id = 14,
                            DataL = new DateTime(2020, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Valorant é um jogo de tiro tático em equipe desenvolvido pela Riot Games. Os jogadores participam de partidas 5v5 onde devem completar objetivos e eliminar o time adversário. Com personagens únicos e habilidades especiais, Valorant combina estratégia e habilidade individual.",
                            Desenvolvedor = "Riot Games",
                            Genero = "Tiro, Estratégia",
                            Nome = "Valorant"
                        },
                        new
                        {
                            Id = 15,
                            DataL = new DateTime(2019, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Apex Legends é um jogo de tiro em equipe no estilo battle royale ambientado no universo do jogo Titanfall. Os jogadores formam esquadrões e competem contra outros times em um mapa repleto de ação. Com personagens únicos, habilidades especiais e um combate dinâmico, Apex Legends conquistou uma grande base de fãs.",
                            Desenvolvedor = "Respawn Entertainment",
                            Genero = "Battle Royale, Tiro",
                            Nome = "Apex Legends"
                        },
                        new
                        {
                            Id = 16,
                            DataL = new DateTime(2018, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Battlefield V é um jogo de tiro em primeira pessoa ambientado na Segunda Guerra Mundial. Os jogadores participam de batalhas multiplayer épicas em cenários históricos, além de vivenciar uma campanha para um jogador emocionante. Com um foco em combate realista e uma ampla variedade de modos de jogo, Battlefield V oferece uma experiência de guerra imersiva.",
                            Desenvolvedor = "DICE",
                            Genero = "Tiro",
                            Nome = "Battlefield V"
                        },
                        new
                        {
                            Id = 17,
                            DataL = new DateTime(1993, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "FIFA é uma série de jogos de simulação de futebol desenvolvida pela EA Sports. Os jogadores podem controlar times e competir em partidas de futebol realistas, com gráficos impressionantes e uma jogabilidade envolvente. Com licenças oficiais de jogadores, times e ligas, FIFA oferece uma experiência autêntica para os fãs de futebol.",
                            Desenvolvedor = "EA Vancouver",
                            Genero = "Esporte, Simulação",
                            Nome = "FIFA"
                        },
                        new
                        {
                            Id = 18,
                            DataL = new DateTime(2016, 5, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Overwatch é um jogo de tiro em equipe desenvolvido pela Blizzard Entertainment. Os jogadores formam times e participam de intensas batalhas multiplayer em um futuro próximo. Com uma variedade de heróis com habilidades únicas, Overwatch combina ação frenética, estratégia e trabalho em equipe.",
                            Desenvolvedor = "Blizzard Entertainment",
                            Genero = "Tiro",
                            Nome = "Overwatch"
                        },
                        new
                        {
                            Id = 19,
                            DataL = new DateTime(2015, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Rainbow Six Siege é um jogo de tiro tático em equipe desenvolvido pela Ubisoft. Os jogadores assumem o papel de agentes de elite e participam de emocionantes confrontos em equipe. Com um foco em estratégia, comunicação e destruição de ambientes, Rainbow Six Siege oferece uma experiência de jogo intensa e repleta de ação.",
                            Desenvolvedor = "Ubisoft Montreal",
                            Genero = "Tiro, Estratégia",
                            Nome = "Rainbow Six Siege"
                        },
                        new
                        {
                            Id = 20,
                            DataL = new DateTime(2017, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "PlayerUnknown's Battlegrounds, comumente conhecido como PUBG, é um jogo de battle royale onde os jogadores lutam entre si em uma ilha até que reste apenas um sobrevivente. Os jogadores devem encontrar armas, equipamentos e veículos enquanto enfrentam outros jogadores em uma luta pela sobrevivência.",
                            Desenvolvedor = "PUBG Corporation",
                            Genero = "Battle Royale, Tiro",
                            Nome = "PlayerUnknown's Battlegrounds (PUBG)"
                        },
                        new
                        {
                            Id = 21,
                            DataL = new DateTime(2012, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Diablo III é um jogo de RPG de ação desenvolvido pela Blizzard Entertainment. Os jogadores assumem o papel de um herói lutando contra as forças do mal, enfrentando hordas de inimigos, coletando tesouros e melhorando suas habilidades. Com uma narrativa envolvente e uma jogabilidade viciante, Diablo III é um dos principais jogos do gênero.",
                            Desenvolvedor = "Blizzard Entertainment",
                            Genero = "RPG, Ação",
                            Nome = "Diablo III"
                        },
                        new
                        {
                            Id = 22,
                            DataL = new DateTime(2018, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Far Cry 5 é um jogo de tiro em primeira pessoa de mundo aberto desenvolvido pela Ubisoft. Ambientado em uma região fictícia dos Estados Unidos, os jogadores devem enfrentar um culto religioso perigoso enquanto exploram o mundo aberto e participam de missões emocionantes. Com uma jogabilidade imersiva e gráficos impressionantes, Far Cry 5 oferece uma experiência de ação intensa.",
                            Desenvolvedor = "Ubisoft Montreal",
                            Genero = "Tiro, Aventura",
                            Nome = "Far Cry 5"
                        },
                        new
                        {
                            Id = 23,
                            DataL = new DateTime(2018, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Red Dead Redemption 2 é um jogo de ação e aventura em mundo aberto desenvolvido pela Rockstar Games. Situado no Velho Oeste, os jogadores assumem o papel de um fora da lei enquanto exploram um vasto mundo, realizam missões, interagem com personagens e vivenciam uma história épica. Com gráficos deslumbrantes e uma jogabilidade imersiva, Red Dead Redemption 2 é uma obra-prima dos jogos.",
                            Desenvolvedor = "Rockstar Games",
                            Genero = "Ação, Aventura",
                            Nome = "Red Dead Redemption 2"
                        },
                        new
                        {
                            Id = 24,
                            DataL = new DateTime(2021, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Resident Evil Village é um jogo de terror e sobrevivência desenvolvido pela Capcom. Continuando a história de Resident Evil 7, os jogadores assumem o papel de Ethan Winters em uma vila assustadora e repleta de perigos. Com uma combinação de combate tenso, quebra-cabeças desafiadores e uma atmosfera sinistra, Resident Evil Village oferece uma experiência aterrorizante.",
                            Desenvolvedor = "Capcom",
                            Genero = "Terror, Sobrevivência",
                            Nome = "Resident Evil Village"
                        },
                        new
                        {
                            Id = 25,
                            DataL = new DateTime(2020, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Cyberpunk 2077 é um jogo de RPG de ação ambientado em um futuro distópico. Os jogadores assumem o papel de V, um mercenário em busca de uma implante lendário que concede imortalidade. Com uma cidade vasta e cheia de possibilidades, escolhas morais significativas e uma história envolvente, Cyberpunk 2077 oferece uma experiência única.",
                            Desenvolvedor = "CD Projekt Red",
                            Genero = "RPG, Ação",
                            Nome = "Cyberpunk 2077"
                        },
                        new
                        {
                            Id = 26,
                            DataL = new DateTime(2020, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Assassin's Creed Valhalla é um jogo de ação e aventura em mundo aberto da série Assassin's Creed. Situado na era dos vikings, os jogadores assumem o papel de Eivor, um guerreiro viking em busca de um novo lar. Com batalhas épicas, exploração de vastos territórios e uma narrativa rica, Assassin's Creed Valhalla oferece uma experiência imersiva no mundo viking.",
                            Desenvolvedor = "Ubisoft Montreal",
                            Genero = "Ação, Aventura",
                            Nome = "Assassin's Creed Valhalla"
                        },
                        new
                        {
                            Id = 27,
                            DataL = new DateTime(2011, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "The Elder Scrolls V: Skyrim é um jogo de RPG de ação em mundo aberto desenvolvido pela Bethesda Game Studios. Os jogadores assumem o papel de um personagem personalizável e embarcam em uma jornada épica em Skyrim, um reino de fantasia repleto de aventuras, missões e perigos. Com uma jogabilidade imersiva e uma rica narrativa, Skyrim é um dos jogos mais aclamados de todos os tempos.",
                            Desenvolvedor = "Bethesda Game Studios",
                            Genero = "RPG, Ação",
                            Nome = "Elder Scrolls V: Skyrim"
                        },
                        new
                        {
                            Id = 28,
                            DataL = new DateTime(2016, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Stardew Valley é um jogo de simulação de fazenda desenvolvido por Eric Barone. Os jogadores assumem o papel de um personagem que herda uma fazenda antiga e precisam administrá-la, cultivando plantações, criando animais, explorando a cidade local, participando de eventos e interagindo com os personagens. Com seu estilo visual encantador e jogabilidade relaxante, Stardew Valley oferece uma experiência de fazenda cativante.",
                            Desenvolvedor = "ConcernedApe",
                            Genero = "Simulação, RPG",
                            Nome = "Stardew Valley"
                        },
                        new
                        {
                            Id = 29,
                            DataL = new DateTime(2015, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Rocket League é um jogo de esporte e ação que combina futebol com carros em uma arena. Os jogadores controlam carros equipados com foguetes e devem marcar gols em uma partida frenética. Com modos de jogo variados, competições online e jogabilidade divertida, Rocket League oferece uma experiência multiplayer emocionante.",
                            Desenvolvedor = "Psyonix",
                            Genero = "Esporte, Ação",
                            Nome = "Rocket League"
                        },
                        new
                        {
                            Id = 30,
                            DataL = new DateTime(2010, 7, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "StarCraft II é um jogo de estratégia em tempo real desenvolvido pela Blizzard Entertainment. Os jogadores assumem o controle de uma das três facções - Terranos, Protoss ou Zergs - e competem em batalhas estratégicas. Com uma campanha envolvente, modos multiplayer competitivos e ferramentas de criação de mapas, StarCraft II é um dos principais jogos de estratégia do mercado.",
                            Desenvolvedor = "Blizzard Entertainment",
                            Genero = "Estratégia",
                            Nome = "StarCraft II"
                        },
                        new
                        {
                            Id = 31,
                            DataL = new DateTime(2020, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Genshin Impact é um jogo de ação e RPG de mundo aberto desenvolvido pela miHoYo. Os jogadores exploram o mundo de Teyvat, lutam contra inimigos, completam missões, desvendam segredos e embarcam em uma jornada para encontrar os membros perdidos de sua família. Com uma jogabilidade de combate dinâmica, belos visuais e uma história envolvente, Genshin Impact oferece uma experiência de aventura emocionante.",
                            Desenvolvedor = "miHoYo",
                            Genero = "Ação, RPG",
                            Nome = "Genshin Impact"
                        },
                        new
                        {
                            Id = 32,
                            DataL = new DateTime(2018, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Monster Hunter: World é um jogo de ação e RPG desenvolvido pela Capcom. Os jogadores assumem o papel de um caçador e embarcam em missões para caçar e derrotar monstros gigantes em um mundo aberto. Com um vasto arsenal de armas e armaduras, combate tático e um sistema de progressão profundo, Monster Hunter: World oferece uma experiência desafiadora para os fãs de caçadas épicas.",
                            Desenvolvedor = "Capcom",
                            Genero = "Ação, RPG",
                            Nome = "Monster Hunter: World"
                        },
                        new
                        {
                            Id = 33,
                            DataL = new DateTime(2015, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "The Witcher 3: Wild Hunt é um jogo de RPG de ação em mundo aberto desenvolvido pela CD Projekt Red. Os jogadores assumem o papel de Geralt de Rivia, um caçador de monstros conhecido como Witcher, e embarcam em uma busca épica em um vasto continente repleto de perigos, escolhas morais e histórias envolventes. Com uma narrativa profunda, combate desafiador e um mundo rico em detalhes, The Witcher 3: Wild Hunt é considerado um dos melhores jogos de todos os tempos.",
                            Desenvolvedor = "CD Projekt Red",
                            Genero = "RPG, Ação",
                            Nome = "The Witcher 3: Wild Hunt"
                        },
                        new
                        {
                            Id = 34,
                            DataL = new DateTime(2019, 4, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Mortal Kombat 11 é um jogo de luta desenvolvido pela NetherRealm Studios. Os jogadores participam de combates intensos e brutais, controlando uma variedade de personagens icônicos da franquia Mortal Kombat. Com gráficos impressionantes, movimentos especiais devastadores e uma história envolvente, Mortal Kombat 11 oferece uma experiência emocionante para os fãs de luta.",
                            Desenvolvedor = "NetherRealm Studios",
                            Genero = "Luta",
                            Nome = "Mortal Kombat 11"
                        },
                        new
                        {
                            Id = 35,
                            DataL = new DateTime(2015, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Fallout 4 é um jogo de RPG de ação desenvolvido pela Bethesda Game Studios. Ambientado em um mundo pós-apocalíptico, os jogadores assumem o papel de um sobrevivente que emerge de um abrigo subterrâneo para explorar e enfrentar os perigos da região de Boston. Com um vasto mundo aberto, escolhas morais impactantes e um sistema de construção de assentamentos, Fallout 4 oferece uma experiência imersiva no universo pós-nuclear.",
                            Desenvolvedor = "Bethesda Game Studios",
                            Genero = "RPG, Ação",
                            Nome = "Fallout 4"
                        },
                        new
                        {
                            Id = 36,
                            DataL = new DateTime(2011, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Terraria é um jogo de ação e aventura com elementos de construção desenvolvido pela Re-Logic. Os jogadores exploram um mundo pixelado em 2D, coletam recursos, constroem estruturas e enfrentam inimigos em diferentes biomas. Com uma jogabilidade sandbox e uma infinidade de itens, armas e chefes para enfrentar, Terraria oferece uma experiência criativa e desafiadora.",
                            Desenvolvedor = "Re-Logic",
                            Genero = "Ação, Aventura",
                            Nome = "Terraria"
                        },
                        new
                        {
                            Id = 37,
                            DataL = new DateTime(2018, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Subnautica é um jogo de exploração e sobrevivência desenvolvido pela Unknown Worlds Entertainment. Os jogadores assumem o papel de um sobrevivente de um acidente espacial e exploram um oceano alienígena repleto de criaturas perigosas e mistérios. Com uma atmosfera imersiva, gráficos impressionantes e uma narrativa cativante, Subnautica oferece uma experiência",
                            Desenvolvedor = "Unknown Worlds Entertainment",
                            Genero = "Exploração, Sobrevivência",
                            Nome = "Subnautica"
                        },
                        new
                        {
                            Id = 38,
                            DataL = new DateTime(2016, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Dark Souls III é um jogo de RPG de ação desenvolvido pela FromSoftware. Situado em um mundo sombrio e repleto de desafios, os jogadores enfrentam inimigos poderosos, chefes intimidadores e exploram cenários detalhados. Com combates estratégicos, uma atmosfera única e uma narrativa envolvente, Dark Souls III proporciona uma experiência intensa e gratificante.",
                            Desenvolvedor = "FromSoftware",
                            Genero = "RPG, Ação",
                            Nome = "Dark Souls III"
                        },
                        new
                        {
                            Id = 39,
                            DataL = new DateTime(2013, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Warframe é um jogo de tiro em terceira pessoa online desenvolvido pela Digital Extremes. Os jogadores assumem o papel de Tennos, guerreiros espaciais que controlam armaduras avançadas conhecidas como Warframes. Com uma jogabilidade cooperativa, combates frenéticos e um sistema de progressão profundo, Warframe oferece uma experiência viciante no universo futurista.",
                            Desenvolvedor = "Digital Extremes",
                            Genero = "Tiro em terceira pessoa, MMO",
                            Nome = "Warframe"
                        },
                        new
                        {
                            Id = 40,
                            DataL = new DateTime(2014, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "The Elder Scrolls Online é um MMORPG desenvolvido pela ZeniMax Online Studios. Situado no universo de fantasia de The Elder Scrolls, os jogadores podem explorar vastas terras, completar missões, lutar contra inimigos e interagir com outros jogadores. Com uma história rica, mecânicas de RPG clássicas e um mundo aberto expansivo, The Elder Scrolls Online oferece uma experiência imersiva no reino de Tamriel.",
                            Desenvolvedor = "ZeniMax Online Studios",
                            Genero = "MMORPG",
                            Nome = "The Elder Scrolls Online"
                        },
                        new
                        {
                            Id = 41,
                            DataL = new DateTime(2012, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Euro Truck Simulator 2 é um simulador de caminhões desenvolvido pela SCS Software. Os jogadores assumem o papel de motoristas de caminhões, transportando cargas por toda a Europa. Com gráficos realistas, uma ampla seleção de caminhões e missões desafiadoras, Euro Truck Simulator 2 proporciona uma experiência autêntica de condução de caminhões.",
                            Desenvolvedor = "SCS Software",
                            Genero = "Simulação",
                            Nome = "Euro Truck Simulator 2"
                        },
                        new
                        {
                            Id = 42,
                            DataL = new DateTime(2013, 4, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Don't Starve é um jogo de sobrevivência desenvolvido pela Klei Entertainment. Os jogadores assumem o papel de Wilson, um cientista preso em um mundo misterioso e perigoso. Eles devem explorar o ambiente, coletar recursos, criar itens e lutar contra criaturas para sobreviver. Com uma estética única, desafios constantes e uma jogabilidade envolvente, Don't Starve oferece uma experiência cativante de sobrevivência.",
                            Desenvolvedor = "Klei Entertainment",
                            Genero = "Sobrevivência",
                            Nome = "Don't Starve"
                        },
                        new
                        {
                            Id = 43,
                            DataL = new DateTime(2019, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Age of Empires II: Definitive Edition é uma versão remasterizada do clássico jogo de estratégia em tempo real Age of Empires II. Os jogadores constroem e expandem impérios, treinam exércitos e lutam contra outras civilizações em batalhas épicas. Com gráficos aprimorados, conteúdo adicional e melhorias de jogabilidade, Age of Empires II: Definitive Edition oferece uma experiência nostálgica e aprofundada para os fãs do gênero.",
                            Desenvolvedor = "Forgotten Empires, Tantalus Media, Wicked Witch",
                            Genero = "Estratégia em tempo real",
                            Nome = "Age of Empires II: Definitive Edition"
                        },
                        new
                        {
                            Id = 44,
                            DataL = new DateTime(2020, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Hades é um jogo de ação e roguelike desenvolvido pela Supergiant Games. Os jogadores assumem o papel de Zagreus, filho do deus grego Hades, enquanto ele tenta escapar do Submundo. Com uma jogabilidade fluida, combates desafiadores e uma narrativa envolvente, Hades oferece uma experiência cativante com elementos mitológicos.",
                            Desenvolvedor = "Supergiant Games",
                            Genero = "Ação, Roguelike",
                            Nome = "Hades"
                        },
                        new
                        {
                            Id = 45,
                            DataL = new DateTime(2017, 9, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Cuphead é um jogo de plataforma e ação desenvolvido pelo Studio MDHR. Com uma estética inspirada em desenhos animados dos anos 1930, os jogadores controlam Cuphead ou Mugman em batalhas contra chefes desafiadores. Com uma jogabilidade precisa, visuais impressionantes e trilha sonora envolvente, Cuphead oferece uma experiência única e desafiadora.",
                            Desenvolvedor = "Studio MDHR",
                            Genero = "Plataforma, Ação",
                            Nome = "Cuphead"
                        },
                        new
                        {
                            Id = 46,
                            DataL = new DateTime(2019, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Resident Evil 2 Remake é um jogo de terror e sobrevivência desenvolvido pela Capcom. O jogo é uma recriação do clássico Resident Evil 2 lançado em 1998. Os jogadores assumem o papel de Leon S. Kennedy e Claire Redfield, enquanto exploram a cidade infestada por zumbis. Com gráficos realistas, jogabilidade modernizada e uma atmosfera tensa, Resident Evil 2 Remake oferece uma experiência assustadora e envolvente.",
                            Desenvolvedor = "Capcom",
                            Genero = "Terror, Sobrevivência",
                            Nome = "Resident Evil 2 Remake"
                        },
                        new
                        {
                            Id = 47,
                            DataL = new DateTime(2017, 2, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "NieR: Automata é um jogo de ação e RPG desenvolvido pela PlatinumGames. Situado em um futuro distópico, os jogadores controlam androides de combate em uma guerra contra máquinas. Com uma narrativa complexa, jogabilidade fluida e uma trilha sonora marcante, NieR: Automata oferece uma experiência emocional e envolvente.",
                            Desenvolvedor = "PlatinumGames",
                            Genero = "Ação, RPG",
                            Nome = "NieR: Automata"
                        },
                        new
                        {
                            Id = 48,
                            DataL = new DateTime(2016, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Dead by Daylight é um jogo de terror multiplayer assimétrico desenvolvido pela Behaviour Interactive. Os jogadores podem assumir o papel de um assassino sanguinário ou de um dos sobreviventes tentando escapar. Com uma jogabilidade única e emocionante, Dead by Daylight oferece uma experiência intensa de perseguição e sobrevivência.",
                            Desenvolvedor = "Behaviour Interactive",
                            Genero = "Terror, Multijogador",
                            Nome = "Dead by Daylight"
                        },
                        new
                        {
                            Id = 49,
                            DataL = new DateTime(2019, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Need for Speed: Heat é um jogo de corrida desenvolvido pela Ghost Games. Ambientado em Palm City, os jogadores participam de corridas ilegais durante o dia para ganhar dinheiro e aprimorar seus carros, e corridas emocionantes à noite para aumentar sua reputação. Com uma ampla seleção de carros, personalização detalhada e perseguições policiais intensas, Need for Speed: Heat oferece uma experiência emocionante para os fãs de corrida.",
                            Desenvolvedor = "Ghost Games",
                            Genero = "Corrida",
                            Nome = "Need for Speed: Heat"
                        },
                        new
                        {
                            Id = 50,
                            DataL = new DateTime(2019, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Tom Clancy's Ghost Recon Breakpoint é um jogo de tiro em mundo aberto desenvolvido pela Ubisoft. Situado em uma ilha fictícia chamada Auroa, os jogadores assumem o papel de um soldado de elite lutando contra um exército mercenário. Com uma jogabilidade tática, elementos de sobrevivência e um modo cooperativo online, Ghost Recon Breakpoint oferece uma experiência de combate emocionante.",
                            Desenvolvedor = "Ubisoft",
                            Genero = "Tiro, Mundo Aberto",
                            Nome = "Tom Clancy's Ghost Recon Breakpoint"
                        },
                        new
                        {
                            Id = 51,
                            DataL = new DateTime(2020, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Doom Eternal é um jogo de tiro em primeira pessoa desenvolvido pela id Software. Os jogadores assumem o papel do Doom Slayer, um guerreiro enfrentando hordas de demônios do inferno. Com uma jogabilidade frenética, armas poderosas e combates intensos, Doom Eternal oferece uma experiência visceral e cheia de ação.",
                            Desenvolvedor = "id Software",
                            Genero = "Tiro em primeira pessoa",
                            Nome = "Doom Eternal"
                        },
                        new
                        {
                            Id = 52,
                            DataL = new DateTime(2011, 8, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Deus Ex: Human Revolution é um jogo de ação e RPG desenvolvido pela Eidos Montreal. Ambientado em um futuro distópico, os jogadores assumem o papel de Adam Jensen, um segurança cibernético com habilidades aprimoradas. Com uma narrativa envolvente, escolhas morais impactantes e jogabilidade que combina ação furtiva e combate, Deus Ex: Human Revolution oferece uma experiência imersiva e cativante.",
                            Desenvolvedor = "Eidos Montreal",
                            Genero = "Ação, RPG",
                            Nome = "Deus Ex: Human Revolution"
                        },
                        new
                        {
                            Id = 53,
                            DataL = new DateTime(2019, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Borderlands 3 é um jogo de tiro em primeira pessoa e RPG de ação desenvolvido pela Gearbox Software. Os jogadores exploram mundos diversos, enfrentam inimigos e completam missões em busca de tesouros e loot. Com um estilo visual único, um elenco de personagens memoráveis e um sistema de armas variado, Borderlands 3 oferece uma experiência cheia de humor e caos.",
                            Desenvolvedor = "Gearbox Software",
                            Genero = "Tiro em primeira pessoa, RPG de ação",
                            Nome = "Borderlands 3"
                        },
                        new
                        {
                            Id = 54,
                            DataL = new DateTime(2019, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Sekiro: Shadows Die Twice é um jogo de ação e aventura desenvolvido pela FromSoftware. Ambientado no Japão feudal, os jogadores assumem o papel de um guerreiro ninja em busca de vingança. Com combates desafiadores, habilidades especiais e uma narrativa envolvente, Sekiro: Shadows Die Twice oferece uma experiência emocionante e exigente.",
                            Desenvolvedor = "FromSoftware",
                            Genero = "Ação, Aventura",
                            Nome = "Sekiro: Shadows Die Twice"
                        },
                        new
                        {
                            Id = 55,
                            DataL = new DateTime(2020, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Half-Life: Alyx é um jogo de realidade virtual desenvolvido pela Valve. Situado no universo de Half-Life, os jogadores assumem o papel de Alyx Vance em uma missão para combater uma invasão alienígena. Com uma narrativa envolvente, jogabilidade imersiva em realidade virtual e quebra-cabeças desafiadores, Half-Life: Alyx redefine a experiência de jogos em VR.",
                            Desenvolvedor = "Valve",
                            Genero = "Ação, Aventura, Realidade Virtual",
                            Nome = "Half-Life: Alyx"
                        },
                        new
                        {
                            Id = 56,
                            DataL = new DateTime(2019, 8, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Control é um jogo de ação e aventura desenvolvido pela Remedy Entertainment. Os jogadores assumem o papel de Jesse Faden, uma mulher com habilidades sobrenaturais, enquanto ela explora um prédio misterioso chamado Oldest House. Com poderes paranormais, combates intensos e uma narrativa intrigante, Control oferece uma experiência única e envolvente.",
                            Desenvolvedor = "Remedy Entertainment",
                            Genero = "Ação, Aventura",
                            Nome = "Control"
                        },
                        new
                        {
                            Id = 57,
                            DataL = new DateTime(2016, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Battlefield 1 é um jogo de tiro em primeira pessoa desenvolvido pela DICE. Ambientado na Primeira Guerra Mundial, os jogadores participam de batalhas épicas em diversos cenários históricos. Com um modo campanha emocionante e um modo multiplayer intenso, Battlefield 1 oferece uma experiência imersiva e repleta de ação.",
                            Desenvolvedor = "DICE",
                            Genero = "Tiro em primeira pessoa",
                            Nome = "Battlefield 1"
                        },
                        new
                        {
                            Id = 58,
                            DataL = new DateTime(2019, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Tom Clancy's The Division 2 é um jogo de tiro em terceira pessoa desenvolvido pela Massive Entertainment. Ambientado em um mundo pós-apocalíptico, os jogadores fazem parte de uma força especial para restaurar a ordem e combater facções hostis. Com um vasto mundo aberto, combates estratégicos e modo multiplayer cooperativo, The Division 2 oferece uma experiência completa e dinâmica.",
                            Desenvolvedor = "Massive Entertainment",
                            Genero = "Tiro em terceira pessoa, RPG de ação",
                            Nome = "Tom Clancy's The Division 2"
                        },
                        new
                        {
                            Id = 59,
                            DataL = new DateTime(2021, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Hitman 3 é um jogo de stealth e ação desenvolvido pela IO Interactive. Como o Agente 47, os jogadores viajam pelo mundo para eliminar alvos usando criatividade, disfarces e habilidades furtivas. Com uma variedade de missões e locais impressionantes, Hitman 3 oferece uma experiência envolvente e desafiadora para os fãs da série.",
                            Desenvolvedor = "IO Interactive",
                            Genero = "Ação, Stealth",
                            Nome = "Hitman 3"
                        },
                        new
                        {
                            Id = 60,
                            DataL = new DateTime(2013, 8, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Final Fantasy XIV é um MMORPG desenvolvido pela Square Enix. Os jogadores embarcam em aventuras épicas em um mundo de fantasia, enfrentando monstros, explorando masmorras e participando de batalhas emocionantes. Com uma história rica, personagens memoráveis e um sistema de classes flexível, Final Fantasy XIV oferece uma experiência online cativante para os fãs da franquia.",
                            Desenvolvedor = "Square Enix",
                            Genero = "MMORPG",
                            Nome = "Final Fantasy XIV"
                        },
                        new
                        {
                            Id = 61,
                            DataL = new DateTime(2021, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Mass Effect: Legendary Edition é uma coletânea remasterizada dos jogos da trilogia Mass Effect, desenvolvida pela BioWare. Os jogadores embarcam em uma jornada épica pelo espaço como o Comandante Shepard, tomando decisões que afetam o destino da galáxia. Com gráficos aprimorados, jogabilidade refinada e todas as DLCs inclusas, Mass Effect: Legendary Edition oferece uma experiência imersiva e emocionante.",
                            Desenvolvedor = "BioWare",
                            Genero = "RPG de ação, Ficção científica",
                            Nome = "Mass Effect: Legendary Edition"
                        },
                        new
                        {
                            Id = 62,
                            DataL = new DateTime(2017, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Destiny 2 é um jogo de tiro em primeira pessoa desenvolvido pela Bungie. Os jogadores exploram o universo fictício e lutam contra inimigos em uma história épica. Com uma campanha envolvente, modos PvP competitivos e desafios PvE cooperativos, Destiny 2 oferece uma experiência online dinâmica e repleta de ação.",
                            Desenvolvedor = "Bungie",
                            Genero = "Tiro em primeira pessoa, MMO",
                            Nome = "Destiny 2"
                        },
                        new
                        {
                            Id = 63,
                            DataL = new DateTime(2020, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Resident Evil 3 Remake é uma reimaginação do clássico jogo de terror desenvolvido pela Capcom. Os jogadores assumem o papel de Jill Valentine enquanto tentam sobreviver a um apocalipse zumbi. Com gráficos realistas, jogabilidade intensa e uma narrativa envolvente, Resident Evil 3 Remake oferece uma experiência assustadora e emocionante.",
                            Desenvolvedor = "Capcom",
                            Genero = "Survival horror",
                            Nome = "Resident Evil 3 Remake"
                        },
                        new
                        {
                            Id = 64,
                            DataL = new DateTime(2006, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "The Elder Scrolls IV: Oblivion é um RPG de mundo aberto desenvolvido pela Bethesda Game Studios. Os jogadores exploram a província de Cyrodiil enquanto embarcam em uma jornada para salvar o reino de Tamriel de uma ameaça demoníaca. Com um vasto mundo, personagens cativantes e uma jogabilidade envolvente, Oblivion é um clássico dos jogos de RPG.",
                            Desenvolvedor = "Bethesda Game Studios",
                            Genero = "RPG de ação, Mundo aberto",
                            Nome = "The Elder Scrolls IV: Oblivion"
                        },
                        new
                        {
                            Id = 65,
                            DataL = new DateTime(2015, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Cities: Skylines é um jogo de construção de cidades desenvolvido pela Colossal Order. Os jogadores têm a tarefa de projetar, construir e gerenciar uma cidade em crescimento, cuidando de aspectos como infraestrutura, serviços públicos e economia. Com uma ampla gama de opções e ferramentas, Cities: Skylines oferece uma experiência detalhada e imersiva para os fãs de simulação urbana.",
                            Desenvolvedor = "Colossal Order",
                            Genero = "Simulação, Construção",
                            Nome = "Cities: Skylines"
                        },
                        new
                        {
                            Id = 66,
                            DataL = new DateTime(2015, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Batman: Arkham Knight é um jogo de ação e aventura desenvolvido pela Rocksteady Studios. Os jogadores assumem o papel do Batman enquanto lutam contra os vilões de Gotham City. Com um combate fluido, um enredo envolvente e gráficos impressionantes, Arkham Knight oferece uma experiência imersiva no mundo do Cavaleiro das Trevas.",
                            Desenvolvedor = "Rocksteady Studios",
                            Genero = "Ação, Aventura",
                            Nome = "Batman: Arkham Knight"
                        },
                        new
                        {
                            Id = 67,
                            DataL = new DateTime(2018, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Detroit: Become Human é um jogo de aventura interativa desenvolvido pela Quantic Dream. Os jogadores assumem o controle de androides em um futuro distópico, tomando decisões que afetam o desenrolar da história. Com uma narrativa complexa e ramificada, gráficos impressionantes e temáticas profundas, Detroit: Become Human oferece uma experiência única e emocional.",
                            Desenvolvedor = "Quantic Dream",
                            Genero = "Aventura, Drama",
                            Nome = "Detroit: Become Human"
                        },
                        new
                        {
                            Id = 68,
                            DataL = new DateTime(2020, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Ori and the Will of the Wisps é um jogo de plataforma e aventura desenvolvido pela Moon Studios. Os jogadores assumem o controle de Ori, um espírito guardião, em sua jornada para descobrir seu destino e salvar a floresta de Nibel. Com visuais deslumbrantes, uma trilha sonora envolvente e mecânicas de jogo refinadas, Ori and the Will of the Wisps é uma experiência emocionante e cativante.",
                            Desenvolvedor = "Moon Studios",
                            Genero = "Plataforma, Aventura",
                            Nome = "Ori and the Will of the Wisps"
                        },
                        new
                        {
                            Id = 69,
                            DataL = new DateTime(2016, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Sid Meier's Civilization VI é um jogo de estratégia por turnos desenvolvido pela Firaxis Games. Os jogadores assumem o papel de líderes de civilizações e devem expandir seus impérios, pesquisar tecnologias, negociar com outras nações e competir pelo domínio global. Com uma jogabilidade profunda, mecânicas desafiadoras e uma rica história, Civilization VI é uma referência no gênero de estratégia.",
                            Desenvolvedor = "Firaxis Games",
                            Genero = "Estratégia",
                            Nome = "Sid Meier's Civilization VI"
                        },
                        new
                        {
                            Id = 70,
                            DataL = new DateTime(2018, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Pillars of Eternity II: Deadfire é um RPG de fantasia desenvolvido pela Obsidian Entertainment. Os jogadores embarcam em uma jornada épica pelos mares, explorando ilhas exóticas, enfrentando criaturas perigosas e tomando decisões que afetam o destino do mundo. Com um sistema de combate tático, uma narrativa envolvente e uma vasta quantidade de escolhas, Pillars of Eternity II oferece uma experiência imersiva para os fãs de RPG.",
                            Desenvolvedor = "Obsidian Entertainment",
                            Genero = "RPG",
                            Nome = "Pillars of Eternity II: Deadfire"
                        },
                        new
                        {
                            Id = 71,
                            DataL = new DateTime(2018, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Kingdom Come: Deliverance é um RPG de mundo aberto realista desenvolvido pela Warhorse Studios. Os jogadores assumem o papel de Henry, um simples camponês que se torna envolvido em uma guerra civil na Boêmia do século XV. Com um foco em realismo histórico, combate desafiador e uma narrativa imersiva, Kingdom Come: Deliverance oferece uma experiência única e envolvente para os fãs de RPG.",
                            Desenvolvedor = "Warhorse Studios",
                            Genero = "RPG de ação, Mundo aberto",
                            Nome = "Kingdom Come: Deliverance"
                        },
                        new
                        {
                            Id = 72,
                            DataL = new DateTime(2016, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Dishonored 2 é um jogo de ação e aventura desenvolvido pela Arkane Studios. Os jogadores assumem o papel de Emily Kaldwin ou Corvo Attano, personagens com habilidades sobrenaturais, em uma missão para restaurar a justiça em uma cidade dominada pela corrupção. Com um sistema de combate flexível, um mundo rico em detalhes e múltiplas abordagens para cada situação, Dishonored 2 oferece liberdade e escolhas para os jogadores.",
                            Desenvolvedor = "Arkane Studios",
                            Genero = "Ação, Aventura",
                            Nome = "Dishonored 2"
                        },
                        new
                        {
                            Id = 73,
                            DataL = new DateTime(2018, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Forza Horizon 4 é um jogo de corrida em mundo aberto desenvolvido pela Playground Games. Os jogadores podem explorar um mundo aberto dinâmico ambientado na Grã-Bretanha, participar de corridas emocionantes, colecionar e personalizar uma variedade de carros e interagir com outros jogadores online. Com gráficos impressionantes, uma ampla variedade de eventos e um sistema de estações que afeta o ambiente de jogo, Forza Horizon 4 oferece uma experiência completa para os fãs de corrida.",
                            Desenvolvedor = "Playground Games",
                            Genero = "Corrida",
                            Nome = "Forza Horizon 4"
                        },
                        new
                        {
                            Id = 74,
                            DataL = new DateTime(2016, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Sid Meier's Civilization VI é um jogo de estratégia por turnos desenvolvido pela Firaxis Games. Os jogadores assumem o papel de líderes de civilizações e devem expandir seus impérios, pesquisar tecnologias, negociar com outras nações e competir pelo domínio global. Com uma jogabilidade profunda, mecânicas desafiadoras e uma rica história, Civilization VI é uma referência no gênero de estratégia.",
                            Desenvolvedor = "Firaxis Games",
                            Genero = "Estratégia",
                            Nome = "Sid Meier's Civilization VI"
                        },
                        new
                        {
                            Id = 75,
                            DataL = new DateTime(2018, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Pillars of Eternity II: Deadfire é um RPG de fantasia desenvolvido pela Obsidian Entertainment. Os jogadores embarcam em uma jornada épica pelos mares, explorando ilhas exóticas, enfrentando criaturas perigosas e tomando decisões que afetam o destino do mundo. Com um sistema de combate tático, uma narrativa envolvente e uma vasta quantidade de escolhas, Pillars of Eternity II oferece uma experiência imersiva para os fãs de RPG.",
                            Desenvolvedor = "Obsidian Entertainment",
                            Genero = "RPG",
                            Nome = "Pillars of Eternity II: Deadfire"
                        },
                        new
                        {
                            Id = 76,
                            DataL = new DateTime(2018, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Kingdom Come: Deliverance é um RPG de mundo aberto realista desenvolvido pela Warhorse Studios. Os jogadores assumem o papel de Henry, um simples camponês que se torna envolvido em uma guerra civil na Boêmia do século XV. Com um foco em realismo histórico, combate desafiador e uma narrativa imersiva, Kingdom Come: Deliverance oferece uma experiência única e envolvente para os fãs de RPG.",
                            Desenvolvedor = "Warhorse Studios",
                            Genero = "RPG de ação, Mundo aberto",
                            Nome = "Kingdom Come: Deliverance"
                        },
                        new
                        {
                            Id = 77,
                            DataL = new DateTime(2016, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Dishonored 2 é um jogo de ação e aventura desenvolvido pela Arkane Studios. Os jogadores assumem o papel de Emily Kaldwin ou Corvo Attano, personagens com habilidades sobrenaturais, em uma missão para restaurar a justiça em uma cidade dominada pela corrupção. Com um sistema de combate flexível, um mundo rico em detalhes e múltiplas abordagens para cada situação, Dishonored 2 oferece liberdade e escolhas para os jogadores.",
                            Desenvolvedor = "Arkane Studios",
                            Genero = "Ação, Aventura",
                            Nome = "Dishonored 2"
                        },
                        new
                        {
                            Id = 78,
                            DataL = new DateTime(2018, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Forza Horizon 4 é um jogo de corrida em mundo aberto desenvolvido pela Playground Games. Os jogadores podem explorar um mundo aberto dinâmico ambientado na Grã-Bretanha, participar de corridas emocionantes, colecionar e personalizar uma variedade de carros e interagir com outros jogadores online. Com gráficos impressionantes, uma ampla variedade de eventos e um sistema de estações que afeta o ambiente de jogo, Forza Horizon 4 oferece uma experiência completa para os fãs de corrida.",
                            Desenvolvedor = "Playground Games",
                            Genero = "Corrida",
                            Nome = "Forza Horizon 4"
                        },
                        new
                        {
                            Id = 79,
                            DataL = new DateTime(2012, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Far Cry 3 é um jogo de tiro em primeira pessoa desenvolvido pela Ubisoft Montreal. Os jogadores assumem o papel de Jason Brody, que fica preso em uma ilha tropical infestada por piratas e deve lutar pela sua sobrevivência. Com um mundo aberto vasto, combate empolgante e uma história envolvente, Far Cry 3 oferece uma experiência emocionante para os fãs de ação.",
                            Desenvolvedor = "Ubisoft Montreal",
                            Genero = "Tiro em primeira pessoa, Mundo aberto",
                            Nome = "Far Cry 3"
                        },
                        new
                        {
                            Id = 80,
                            DataL = new DateTime(2019, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "The Outer Worlds é um RPG de ação desenvolvido pela Obsidian Entertainment. Ambientado em um futuro distante, os jogadores exploram uma série de planetas e participam de uma história repleta de escolhas e consequências. Com um estilo de jogo semelhante aos clássicos RPGs de ação, diálogos marcantes e uma narrativa envolvente, The Outer Worlds oferece uma experiência única e cativante.",
                            Desenvolvedor = "Obsidian Entertainment",
                            Genero = "RPG de ação",
                            Nome = "The Outer Worlds"
                        },
                        new
                        {
                            Id = 81,
                            DataL = new DateTime(2015, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Dying Light é um jogo de sobrevivência e ação em primeira pessoa desenvolvido pela Techland. Ambientado em um mundo pós-apocalíptico infestado por zumbis, os jogadores devem usar suas habilidades de parkour e combate para sobreviver e explorar o ambiente hostil. Com uma jogabilidade frenética, modo cooperativo e um ciclo dia/noite que afeta o gameplay, Dying Light proporciona uma experiência intensa e emocionante.",
                            Desenvolvedor = "Techland",
                            Genero = "Sobrevivência, Ação",
                            Nome = "Dying Light"
                        },
                        new
                        {
                            Id = 82,
                            DataL = new DateTime(2017, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Hollow Knight é um jogo de plataforma e ação desenvolvido pela Team Cherry. Os jogadores exploram um vasto subterrâneo repleto de insetos e mistérios, enfrentando desafios e chefes poderosos. Com uma atmosfera única, gráficos belíssimos e uma trilha sonora envolvente, Hollow Knight cativa os jogadores com sua jogabilidade fluida e desafiadora.",
                            Desenvolvedor = "Team Cherry",
                            Genero = "Plataforma, Ação",
                            Nome = "Hollow Knight"
                        },
                        new
                        {
                            Id = 83,
                            DataL = new DateTime(2019, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "A Plague Tale: Innocence é um jogo de aventura e ação desenvolvido pela Asobo Studio. Ambientado na França medieval, os jogadores controlam Amicia e seu irmão Hugo em uma jornada perigosa e emocionante durante a epidemia de peste negra. Com uma narrativa cativante, gráficos impressionantes e uma jogabilidade baseada em stealth, A Plague Tale: Innocence oferece uma experiência imersiva e comovente.",
                            Desenvolvedor = "Asobo Studio",
                            Genero = "Aventura, Ação",
                            Nome = "A Plague Tale: Innocence"
                        },
                        new
                        {
                            Id = 84,
                            DataL = new DateTime(2017, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "The Legend of Zelda: Breath of the Wild é um jogo de ação e aventura desenvolvido pela Nintendo. Nesta versão emulada, os jogadores podem explorar o vasto mundo de Hyrule, enfrentar desafios e desvendar segredos em uma jornada épica. Com gráficos deslumbrantes, jogabilidade envolvente e uma história cativante, Breath of the Wild proporciona uma experiência inesquecível para os fãs da franquia.",
                            Desenvolvedor = "Nintendo",
                            Genero = "Ação, Aventura",
                            Nome = "The Legend of Zelda: Breath of the Wild (emulador)"
                        },
                        new
                        {
                            Id = 85,
                            DataL = new DateTime(2020, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Command & Conquer Remastered Collection é uma coletânea remasterizada dos clássicos jogos de estratégia em tempo real da série Command & Conquer. Os jogadores podem reviver a ação e a estratégia dos jogos originais, agora com gráficos atualizados e melhorias na jogabilidade. Com campanhas emocionantes e multiplayer competitivo, esta coleção é um deleite para os fãs de estratégia.",
                            Desenvolvedor = "Petroglyph",
                            Genero = "Estratégia em tempo real",
                            Nome = "Command & Conquer Remastered Collection"
                        },
                        new
                        {
                            Id = 86,
                            DataL = new DateTime(2017, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Divinity: Original Sin II é um RPG de fantasia desenvolvido pela Larian Studios. Os jogadores podem criar seus próprios personagens e embarcar em uma jornada épica repleta de escolhas e consequências. Com um sistema de combate estratégico por turnos, interação detalhada com o ambiente e uma narrativa rica, Divinity: Original Sin II oferece uma experiência imersiva e envolvente.",
                            Desenvolvedor = "Larian Studios",
                            Genero = "RPG",
                            Nome = "Divinity: Original Sin II"
                        },
                        new
                        {
                            Id = 87,
                            DataL = new DateTime(2020, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Baldur's Gate III é um RPG de aventura desenvolvido pela Larian Studios. Ambientado no universo de Forgotten Realms, os jogadores embarcam em uma jornada épica repleta de magia, perigos e escolhas morais. Com um sistema de combate estratégico, personagens cativantes e uma narrativa envolvente, Baldur's Gate III oferece uma experiência imersiva para os fãs do gênero.",
                            Desenvolvedor = "Larian Studios",
                            Genero = "RPG, Aventura",
                            Nome = "Baldur's Gate III"
                        },
                        new
                        {
                            Id = 88,
                            DataL = new DateTime(2020, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Mount & Blade II: Bannerlord é um RPG de ação e estratégia desenvolvido pela TaleWorlds Entertainment. Ambientado em um mundo medieval fictício, os jogadores podem assumir o papel de um guerreiro, liderar exércitos, conquistar territórios e participar de batalhas épicas. Com um sistema de combate realista e uma ampla liberdade de escolhas, Bannerlord oferece uma experiência única no gênero.",
                            Desenvolvedor = "TaleWorlds Entertainment",
                            Genero = "RPG, Estratégia",
                            Nome = "Mount & Blade II: Bannerlord"
                        },
                        new
                        {
                            Id = 89,
                            DataL = new DateTime(2019, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Star Wars Jedi: Fallen Order é um jogo de ação e aventura desenvolvido pela Respawn Entertainment. Os jogadores assumem o papel de um jovem Padawan em fuga enquanto explora planetas, enfrenta inimigos e desenvolve habilidades Jedi. Com uma história envolvente, combates emocionantes e elementos de plataforma, Fallen Order proporciona uma experiência autêntica de Star Wars.",
                            Desenvolvedor = "Respawn Entertainment",
                            Genero = "Ação, Aventura",
                            Nome = "Star Wars Jedi: Fallen Order"
                        },
                        new
                        {
                            Id = 90,
                            DataL = new DateTime(2018, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "The Forest é um jogo de sobrevivência em mundo aberto desenvolvido pela Endnight Games. Os jogadores encontram-se em uma ilha deserta após um acidente de avião e devem explorar, construir abrigos, caçar e lutar contra ameaças para sobreviver. Com elementos de terror e uma narrativa misteriosa, The Forest oferece uma experiência desafiadora e imersiva.",
                            Desenvolvedor = "Endnight Games",
                            Genero = "Sobrevivência, Terror",
                            Nome = "The Forest"
                        },
                        new
                        {
                            Id = 91,
                            DataL = new DateTime(2021, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Little Nightmares II é um jogo de quebra-cabeças e horror desenvolvido pela Tarsier Studios. Os jogadores controlam Mono, um garoto preso em um mundo distorcido, enquanto desvendam segredos sombrios e enfrentam ameaças assustadoras. Com uma atmosfera única, visuais deslumbrantes e uma jogabilidade cativante, Little Nightmares II proporciona uma experiência arrepiante.",
                            Desenvolvedor = "Tarsier Studios",
                            Genero = "Quebra-cabeças, Horror",
                            Nome = "Little Nightmares II"
                        },
                        new
                        {
                            Id = 92,
                            DataL = new DateTime(2017, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Resident Evil 7: Biohazard é um jogo de terror em primeira pessoa desenvolvido pela Capcom. Os jogadores assumem o papel de Ethan Winters, que busca sua esposa desaparecida em uma mansão isolada infestada de criaturas grotescas. Com uma atmosfera aterrorizante, quebra-cabeças desafiadores e uma narrativa envolvente, Resident Evil 7 oferece uma reinvenção assustadora da famosa franquia.",
                            Desenvolvedor = "Capcom",
                            Genero = "Terror, Ação",
                            Nome = "Resident Evil 7: Biohazard"
                        },
                        new
                        {
                            Id = 93,
                            DataL = new DateTime(2020, 3, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Nioh 2 é um jogo de ação e RPG desenvolvido pela Team Ninja. Os jogadores embarcam em uma jornada no Japão feudal, enfrentando demônios e desafiando poderosos chefes. Com um combate intenso, personalização de personagens e uma atmosfera imersiva, Nioh 2 proporciona uma experiência desafiadora para os fãs do gênero.",
                            Desenvolvedor = "Team Ninja",
                            Genero = "Ação, RPG",
                            Nome = "Nioh 2"
                        },
                        new
                        {
                            Id = 94,
                            DataL = new DateTime(2019, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Disco Elysium é um jogo de RPG e aventura desenvolvido pela ZA/UM. Os jogadores assumem o papel de um detetive em um mundo distópico, investigando crimes e desvendando uma narrativa complexa. Com escolhas impactantes, diálogos profundos e uma atmosfera única, Disco Elysium oferece uma experiência imersiva e envolvente.",
                            Desenvolvedor = "ZA/UM",
                            Genero = "RPG, Aventura",
                            Nome = "Disco Elysium"
                        },
                        new
                        {
                            Id = 95,
                            DataL = new DateTime(2020, 10, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Watch Dogs: Legion é um jogo de ação e aventura em mundo aberto desenvolvido pela Ubisoft Toronto. Os jogadores assumem o controle de uma resistência hacker em uma versão futurista de Londres, recrutando e controlando diversos personagens para combater uma opressiva corporação. Com um sistema de recrutamento inovador e uma jogabilidade dinâmica, Watch Dogs: Legion oferece uma experiência cativante.",
                            Desenvolvedor = "Ubisoft Toronto",
                            Genero = "Ação, Aventura",
                            Nome = "Watch Dogs: Legion"
                        },
                        new
                        {
                            Id = 96,
                            DataL = new DateTime(2019, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Metro Exodus é um jogo de tiro em primeira pessoa desenvolvido pela 4A Games. Os jogadores exploram ambientes pós-apocalípticos, enfrentando mutantes e sobrevivendo em um mundo hostil. Com uma narrativa envolvente, combate realista e gráficos impressionantes, Metro Exodus proporciona uma experiência imersiva e tensa.",
                            Desenvolvedor = "4A Games",
                            Genero = "Tiro, Ação",
                            Nome = "Metro Exodus"
                        },
                        new
                        {
                            Id = 97,
                            DataL = new DateTime(2021, 4, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "NieR Replicant ver.1.22474487139 é uma versão remasterizada do jogo de ação e RPG desenvolvido pela Square Enix. Os jogadores seguem a jornada de um jovem em busca de uma cura para sua irmã doente, explorando um mundo pós-apocalíptico e enfrentando desafios emocionantes. Com uma história envolvente, personagens cativantes e melhorias gráficas, NieR Replicant oferece uma experiência nostálgica para os fãs do jogo original.",
                            Desenvolvedor = "Square Enix",
                            Genero = "Ação, RPG",
                            Nome = "NieR Replicant ver.1.22474487139"
                        },
                        new
                        {
                            Id = 99,
                            DataL = new DateTime(2005, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Resident Evil 4 é um jogo de ação e terror desenvolvido pela Capcom. Os jogadores assumem o papel de Leon S. Kennedy, que é enviado em uma missão para resgatar a filha do presidente dos Estados Unidos de um culto sinistro. Com uma jogabilidade intensa, puzzles desafiadores e uma atmosfera assustadora, Resident Evil 4 é considerado um dos melhores jogos da franquia.",
                            Desenvolvedor = "Capcom",
                            Genero = "Ação, Terror",
                            Nome = "Resident Evil 4"
                        },
                        new
                        {
                            Id = 100,
                            DataL = new DateTime(2014, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Dragon Age: Inquisition é um jogo de RPG desenvolvido pela BioWare. Os jogadores assumem o papel de um inquisidor, liderando uma equipe de heróis em uma missão para salvar o mundo de uma ameaça sobrenatural. Com um vasto mundo aberto, escolhas impactantes e um sistema de combate estratégico, Dragon Age: Inquisition oferece uma experiência imersiva e épica.",
                            Desenvolvedor = "BioWare",
                            Genero = "RPG",
                            Nome = "Dragon Age: Inquisition"
                        },
                        new
                        {
                            Id = 101,
                            DataL = new DateTime(2021, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "F1 2021 é um jogo de corrida desenvolvido pela Codemasters. Os jogadores podem vivenciar a emoção e a intensidade do Campeonato Mundial de Fórmula 1, competindo contra pilotos reais e equipes renomadas. Com gráficos realistas, mecânicas de corrida autênticas e modos de jogo variados, F1 2021 oferece uma experiência completa para os fãs do esporte.",
                            Desenvolvedor = "Codemasters",
                            Genero = "Corrida",
                            Nome = "F1 2021"
                        },
                        new
                        {
                            Id = 102,
                            DataL = new DateTime(2019, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Oxygen Not Included é um jogo de simulação e sobrevivência desenvolvido pela Klei Entertainment. Os jogadores assumem o controle de colonos em um asteroide distante, gerenciando recursos, construindo estruturas e lidando com os desafios do ambiente hostil. Com uma jogabilidade complexa e desafiadora, Oxygen Not Included oferece uma experiência viciante para os fãs do gênero.",
                            Desenvolvedor = "Klei Entertainment",
                            Genero = "Simulação, Sobrevivência",
                            Nome = "Oxygen Not Included"
                        },
                        new
                        {
                            Id = 103,
                            DataL = new DateTime(2021, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Subnautica: Below Zero é um jogo de aventura e sobrevivência desenvolvido pela Unknown Worlds Entertainment. Os jogadores exploram um mundo subaquático gelado, coletando recursos, construindo bases e desvendando os mistérios do ambiente. Com uma narrativa envolvente e uma atmosfera imersiva, Subnautica: Below Zero oferece uma experiência única no fundo do oceano.",
                            Desenvolvedor = "Unknown Worlds Entertainment",
                            Genero = "Aventura, Sobrevivência",
                            Nome = "Subnautica: Below Zero"
                        },
                        new
                        {
                            Id = 104,
                            DataL = new DateTime(2010, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "World of Tanks é um jogo de guerra online desenvolvido pela Wargaming. Nele, os jogadores controlam tanques de guerra e participam de batalhas épicas em equipes. Com uma ampla variedade de veículos, táticas estratégicas e combates emocionantes, World of Tanks oferece uma experiência multiplayer intensa.",
                            Desenvolvedor = "Wargaming",
                            Genero = "Ação, Estratégia",
                            Nome = "World of Tanks"
                        },
                        new
                        {
                            Id = 105,
                            DataL = new DateTime(2020, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Ghost of Tsushima é um jogo de ação e aventura desenvolvido pela Sucker Punch Productions. Os jogadores assumem o papel de Jin Sakai, um samurai em uma missão para proteger a ilha de Tsushima durante a invasão mongol. Com um mundo aberto deslumbrante, combates de espada precisos e uma narrativa cativante, Ghost of Tsushima oferece uma experiência imersiva no Japão feudal.",
                            Desenvolvedor = "Sucker Punch Productions",
                            Genero = "Ação, Aventura",
                            Nome = "Ghost of Tsushima"
                        },
                        new
                        {
                            Id = 106,
                            DataL = new DateTime(2015, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Tom Clancy's Rainbow Six: Siege é um jogo de tiro tático desenvolvido pela Ubisoft Montreal. Os jogadores participam de intensas partidas multiplayer em equipes, onde estratégia, trabalho em equipe e precisão são fundamentais. Com uma grande variedade de operadores e mapas, Rainbow Six: Siege oferece uma experiência competitiva e emocionante.",
                            Desenvolvedor = "Ubisoft Montreal",
                            Genero = "Tiro, Estratégia",
                            Nome = "Tom Clancy's Rainbow Six: Siege"
                        },
                        new
                        {
                            Id = 107,
                            DataL = new DateTime(2017, 8, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "ARK: Survival Evolved é um jogo de sobrevivência em um mundo aberto repleto de dinossauros e criaturas pré-históricas. Os jogadores devem explorar, caçar, criar e construir suas bases para sobreviver nesse ambiente hostil. Com um vasto mapa para explorar e uma grande variedade de dinossauros para domar, ARK: Survival Evolved oferece uma experiência única de sobrevivência.",
                            Desenvolvedor = "Studio Wildcard",
                            Genero = "Aventura, Sobrevivência",
                            Nome = "ARK: Survival Evolved"
                        },
                        new
                        {
                            Id = 108,
                            DataL = new DateTime(2018, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Assassin's Creed Odyssey é um jogo de ação e aventura desenvolvido pela Ubisoft. Ambientado na Grécia Antiga, os jogadores assumem o papel de um mercenário e embarcam em uma jornada épica repleta de combates, exploração e escolhas que afetam a narrativa. Com um vasto mundo aberto, batalhas emocionantes e uma história envolvente, Assassin's Creed Odyssey oferece uma experiência imersiva no universo da série.",
                            Desenvolvedor = "Ubisoft",
                            Genero = "Ação, Aventura",
                            Nome = "Assassin's Creed Odyssey"
                        });
                });

            modelBuilder.Entity("MyApi.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataAcesso")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("PasswordString")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Perfil")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Usuario");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("JogoUsuario", b =>
                {
                    b.HasOne("MyApi.Models.Jogo", null)
                        .WithMany()
                        .HasForeignKey("JogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyApi.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyApi.Models.Favorito", b =>
                {
                    b.HasOne("MyApi.Models.Jogo", "Jogo")
                        .WithMany()
                        .HasForeignKey("JogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyApi.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jogo");

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
